extern const GeoLayout mario_run_b_RunningB_B_geo[];
extern const GeoLayout mario_run_b_RunningC_B_geo[];
extern const GeoLayout mario_run_b_geo[];
extern u8 mario_run_b_mfor1_ci4[];
extern u8 mario_run_b_mfor1_pal_rgba16[];
extern u8 mario_run_b_mfor2_ci4[];
extern u8 mario_run_b_mfor2_pal_rgba16[];
extern u8 mario_run_b_mfor3_ci4[];
extern u8 mario_run_b_mfor3_pal_rgba16[];
extern Vtx mario_run_b_RunningA_B_mesh_layer_4_vtx_0[4];
extern Gfx mario_run_b_RunningA_B_mesh_layer_4_tri_0[];
extern Vtx mario_run_b_RunningB_B_mesh_layer_4_vtx_0[4];
extern Gfx mario_run_b_RunningB_B_mesh_layer_4_tri_0[];
extern Vtx mario_run_b_RunningC_B_mesh_layer_4_vtx_0[4];
extern Gfx mario_run_b_RunningC_B_mesh_layer_4_tri_0[];
extern Gfx mat_mario_run_b_f3dlite_material_009[];
extern Gfx mat_revert_mario_run_b_f3dlite_material_009[];
extern Gfx mat_mario_run_b_f3dlite_material_011[];
extern Gfx mat_revert_mario_run_b_f3dlite_material_011[];
extern Gfx mat_mario_run_b_f3dlite_material_010[];
extern Gfx mat_revert_mario_run_b_f3dlite_material_010[];
extern Gfx mario_run_b_RunningA_B_mesh_layer_4[];
extern Gfx mario_run_b_RunningB_B_mesh_layer_4[];
extern Gfx mario_run_b_RunningC_B_mesh_layer_4[];
