extern const GeoLayout mario_run_l_RunningB_L_geo[];
extern const GeoLayout mario_run_l_RunningC_L_geo[];
extern const GeoLayout mario_run_l_geo[];
extern u8 mario_run_l_m3_ci4[];
extern u8 mario_run_l_m3_pal_rgba16[];
extern u8 mario_run_l_m2_ci4[];
extern u8 mario_run_l_m2_pal_rgba16[];
extern u8 mario_run_l_m1_ci4[];
extern u8 mario_run_l_m1_pal_rgba16[];
extern Vtx mario_run_l_RunningA_L_mesh_layer_4_vtx_0[4];
extern Gfx mario_run_l_RunningA_L_mesh_layer_4_tri_0[];
extern Vtx mario_run_l_RunningB_L_mesh_layer_4_vtx_0[4];
extern Gfx mario_run_l_RunningB_L_mesh_layer_4_tri_0[];
extern Vtx mario_run_l_RunningC_L_mesh_layer_4_vtx_0[4];
extern Gfx mario_run_l_RunningC_L_mesh_layer_4_tri_0[];
extern Gfx mat_mario_run_l_f3dlite_material_014[];
extern Gfx mat_revert_mario_run_l_f3dlite_material_014[];
extern Gfx mat_mario_run_l_f3dlite_material_012[];
extern Gfx mat_revert_mario_run_l_f3dlite_material_012[];
extern Gfx mat_mario_run_l_f3dlite_material_013[];
extern Gfx mat_revert_mario_run_l_f3dlite_material_013[];
extern Gfx mario_run_l_RunningA_L_mesh_layer_4[];
extern Gfx mario_run_l_RunningB_L_mesh_layer_4[];
extern Gfx mario_run_l_RunningC_L_mesh_layer_4[];
