extern const GeoLayout mario_fall_FallForwards_geo[];
extern const GeoLayout mario_fall_FallLeft_geo[];
extern const GeoLayout mario_fall_FallRight_geo[];
extern const GeoLayout mario_fall_geo[];
extern u8 mario_fall_mforfall_ci4[];
extern u8 mario_fall_mforfall_pal_rgba16[];
extern u8 mario_fall_mbackfall_ci4[];
extern u8 mario_fall_mbackfall_pal_rgba16[];
extern u8 mario_fall_mfall_ci4[];
extern u8 mario_fall_mfall_pal_rgba16[];
extern Vtx mario_fall_FallBackwards_mesh_layer_4_vtx_0[4];
extern Gfx mario_fall_FallBackwards_mesh_layer_4_tri_0[];
extern Vtx mario_fall_FallForwards_mesh_layer_4_vtx_0[4];
extern Gfx mario_fall_FallForwards_mesh_layer_4_tri_0[];
extern Vtx mario_fall_FallLeft_mesh_layer_4_vtx_0[4];
extern Gfx mario_fall_FallLeft_mesh_layer_4_tri_0[];
extern Vtx mario_fall_FallRight_mesh_layer_4_vtx_0[4];
extern Gfx mario_fall_FallRight_mesh_layer_4_tri_0[];
extern Gfx mat_mario_fall_f3dlite_material_016[];
extern Gfx mat_revert_mario_fall_f3dlite_material_016[];
extern Gfx mat_mario_fall_f3dlite_material_015[];
extern Gfx mat_revert_mario_fall_f3dlite_material_015[];
extern Gfx mat_mario_fall_f3dlite_material_022[];
extern Gfx mat_revert_mario_fall_f3dlite_material_022[];
extern Gfx mario_fall_FallBackwards_mesh_layer_4[];
extern Gfx mario_fall_FallForwards_mesh_layer_4[];
extern Gfx mario_fall_FallLeft_mesh_layer_4[];
extern Gfx mario_fall_FallRight_mesh_layer_4[];
