extern const GeoLayout mario_run_r_RunningB_R_geo[];
extern const GeoLayout mario_run_r_RunningC_R_geo[];
extern const GeoLayout mario_run_r_geo[];
extern u8 mario_run_r_m3_ci4[];
extern u8 mario_run_r_m3_pal_rgba16[];
extern u8 mario_run_r_m2_ci4[];
extern u8 mario_run_r_m2_pal_rgba16[];
extern u8 mario_run_r_m1_ci4[];
extern u8 mario_run_r_m1_pal_rgba16[];
extern Vtx mario_run_r_RunningA_R_mesh_layer_4_vtx_0[4];
extern Gfx mario_run_r_RunningA_R_mesh_layer_4_tri_0[];
extern Vtx mario_run_r_RunningB_R_mesh_layer_4_vtx_0[4];
extern Gfx mario_run_r_RunningB_R_mesh_layer_4_tri_0[];
extern Vtx mario_run_r_RunningC_R_mesh_layer_4_vtx_0[4];
extern Gfx mario_run_r_RunningC_R_mesh_layer_4_tri_0[];
extern Gfx mat_mario_run_r_f3dlite_material_014[];
extern Gfx mat_revert_mario_run_r_f3dlite_material_014[];
extern Gfx mat_mario_run_r_f3dlite_material_012[];
extern Gfx mat_revert_mario_run_r_f3dlite_material_012[];
extern Gfx mat_mario_run_r_f3dlite_material_013[];
extern Gfx mat_revert_mario_run_r_f3dlite_material_013[];
extern Gfx mario_run_r_RunningA_R_mesh_layer_4[];
extern Gfx mario_run_r_RunningB_R_mesh_layer_4[];
extern Gfx mario_run_r_RunningC_R_mesh_layer_4[];
