extern const GeoLayout mario_idle_IdleForwards_geo[];
extern const GeoLayout mario_idle_IdleLeft_geo[];
extern const GeoLayout mario_idle_IdleRight_geo[];
extern const GeoLayout mario_idle_geo[];
extern u8 mario_idle_mfor2_ci4[];
extern u8 mario_idle_mfor2_pal_rgba16[];
extern u8 mario_idle_mback2_ci4[];
extern u8 mario_idle_mback2_pal_rgba16[];
extern u8 mario_idle_m1_ci4[];
extern u8 mario_idle_m1_pal_rgba16[];
extern u8 mario_idle_m1_ci4_copy[];
extern u8 mario_idle_m1_pal_rgba16_copy[];
extern Vtx mario_idle_IdleBackwards_mesh_layer_4_vtx_0[4];
extern Gfx mario_idle_IdleBackwards_mesh_layer_4_tri_0[];
extern Vtx mario_idle_IdleForwards_mesh_layer_4_vtx_0[4];
extern Gfx mario_idle_IdleForwards_mesh_layer_4_tri_0[];
extern Vtx mario_idle_IdleLeft_mesh_layer_4_vtx_0[4];
extern Gfx mario_idle_IdleLeft_mesh_layer_4_tri_0[];
extern Vtx mario_idle_IdleRight_mesh_layer_4_vtx_0[4];
extern Gfx mario_idle_IdleRight_mesh_layer_4_tri_0[];
extern Gfx mat_mario_idle_f3dlite_material_002[];
extern Gfx mat_revert_mario_idle_f3dlite_material_002[];
extern Gfx mat_mario_idle_f3dlite_material[];
extern Gfx mat_revert_mario_idle_f3dlite_material[];
extern Gfx mat_mario_idle_f3dlite_material_004[];
extern Gfx mat_revert_mario_idle_f3dlite_material_004[];
extern Gfx mat_mario_idle_f3dlite_material_003[];
extern Gfx mat_revert_mario_idle_f3dlite_material_003[];
extern Gfx mario_idle_IdleBackwards_mesh_layer_4[];
extern Gfx mario_idle_IdleForwards_mesh_layer_4[];
extern Gfx mario_idle_IdleLeft_mesh_layer_4[];
extern Gfx mario_idle_IdleRight_mesh_layer_4[];
