extern const GeoLayout mario_run_f_RunningB_F_geo[];
extern const GeoLayout mario_run_f_RunningC_F_geo[];
extern const GeoLayout mario_run_f_geo[];
extern u8 mario_run_f_mback3_ci4[];
extern u8 mario_run_f_mback3_pal_rgba16[];
extern u8 mario_run_f_mback2_ci4[];
extern u8 mario_run_f_mback2_pal_rgba16[];
extern u8 mario_run_f_mback1_ci4[];
extern u8 mario_run_f_mback1_pal_rgba16[];
extern Vtx mario_run_f_RunningA_F_mesh_layer_4_vtx_0[4];
extern Gfx mario_run_f_RunningA_F_mesh_layer_4_tri_0[];
extern Vtx mario_run_f_RunningB_F_mesh_layer_4_vtx_0[4];
extern Gfx mario_run_f_RunningB_F_mesh_layer_4_tri_0[];
extern Vtx mario_run_f_RunningC_F_mesh_layer_4_vtx_0[4];
extern Gfx mario_run_f_RunningC_F_mesh_layer_4_tri_0[];
extern Gfx mat_mario_run_f_f3dlite_material_008[];
extern Gfx mat_revert_mario_run_f_f3dlite_material_008[];
extern Gfx mat_mario_run_f_f3dlite_material[];
extern Gfx mat_revert_mario_run_f_f3dlite_material[];
extern Gfx mat_mario_run_f_f3dlite_material_005[];
extern Gfx mat_revert_mario_run_f_f3dlite_material_005[];
extern Gfx mario_run_f_RunningA_F_mesh_layer_4[];
extern Gfx mario_run_f_RunningB_F_mesh_layer_4[];
extern Gfx mario_run_f_RunningC_F_mesh_layer_4[];
